config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Write a simple route to serve the GET /ask HTTP request to the ask action of the questions controller.
  get "ask", to: "questions#ask", as: 'asking_question'

   # Write a simple route to serve the get/answer request to the answer controller.
  get "answer", to: "answers#answer"


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def answer
    @user_question = params[:question]
    if @user_question == "I am going to work"
      @user_question
      @user_answer = "Great!"
    elsif @user_question&.end_with?("?")
      @user_question
      @user_answer = "Silly question, get dressed and go to work!"
    else
      @user_question
      @user_answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/answer.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">User Question</h5>
          <p class="card-text"><%= @user_question %></p>
        </div>
      </div>
    </div>

    <div class="col-12 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Answer</h5>
          <p class="card-text"><%= @user_answer %></p>
          <%= link_to "back to questions", asking_question_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/ask.html.erb
<h1>Your questions here</h1>

<div>
  <form action="/answer" data-turbo="false" class="form-group">
    <div class="col-md-4">
      <input type="text" class="form-control mb-3" placeholder="Enter text" name="question">
      <input type="submit" value="Ask!" class="btn btn-primary">
    </div>
  </form>
</div>

<!-- 1. Controller gets the parameter. 2. If condition depending on question, display different answers. 3. Display also answers -->